### ISSUE TITLE
cosmic-settings became more laggy

### ISSUE THREAD

**Issue by farhatizakaria** [Fingel/cosmic-themes-org-py#2]
I have tried Gruvbox Dark, when I change accent colors, application/window background... cosmic-settings became more laggy and difficult to deal with colors tweaking. I'm not sure if it's not recommended to customize colors with these themes !

**Comment by Fingel** [comment]
Have you tried restarting your cosmic session? I have doubts that this would be related to the colors scheme.

**Comment by farhatizakaria** [comment]
Yeah, I have restarted it, and my fix was just using the default theme from the website. Now, I can customize colors smoothly
