### ISSUE TITLE
Complains that my exported ron file is not a valid ron file.

### ISSUE THREAD

**Issue by snaggen** [Fingel/cosmic-themes-org-py#7]
I exported my Cosmic Alpha 3 theme and tried to upload it as
Gruvbox Material Dark
Author: Sainnhe Park 
Link: https://github.com/sainnhe/gruvbox-material

But when I try to upload it to https://cosmic-themes.org/ it complains that is is not a valid ron file. 

I attach it here, but compressed with GZip since github refuses to attach a ron file. 
[GruvboxMaterialDark.ron.gz](https://github.com/user-attachments/files/17600444/GruvboxMaterialDark.ron.gz)

**Comment by Fingel** [comment]
This .ron does seem to have a different set of keys than other themes. The error output is:

`Failed to parse theme: SpannedError { code: MissingStructField { field: "blue", outer: Some("CosmicPaletteInner") }, position: Position { line: 196, col: 5 } }`

See the other themes ron files (they are just text) as comparison.

I wonder if the color keys have changed?

**Comment by ryanabx** [comment]
Good timing, I had the same problem!

My theme:

[defaultdarker.ron.txt](https://github.com/user-attachments/files/17605868/defaultdarker.ron.txt)

**Comment by Fingel** [comment]
Looks like this did it:
https://github.com/pop-os/libcosmic/commit/478f3ead755da1c504167961def9954cd58a2b23

I'll try and get a fix in tomorrow. Hopefully it doesn't involve invalidating all the previously uploaded themes.

**Comment by Fingel** [comment]
@snaggen  I did an update, and it looks like your theme parses correctly now: https://cosmic-themes.org/100/ also congrats on theme #100 :+1: 

@ryanabx try again?

**Comment by ryanabx** [comment]
It's working now. Thanks!
