### ISSUE TITLE
Updated Gruvbox Material Dark

### ISSUE THREAD

**Issue by snaggen** [Fingel/cosmic-themes-org-py#8]
I updated the Gruvbox Material Dark theme, and hand edited all the colors in the ron file to be based on the Gruvbox Material Palette. Not sure how to verify all of those, but at least they are based on the palette... 

[GruvboxMaterialDark.ron.gz](https://github.com/user-attachments/files/17630164/GruvboxMaterialDark.ron.gz)

**Comment by Fingel** [comment]
Updated!
